baseURL = ''
relativeURLs = 'True'
languageCode = 'en-us'
title = 'HunterM64'
theme = 'blank'
pluralizeListTitles = false

[markup.goldmark.renderer]
unsafe= true

[params]
    mainSections = ['media-thread', 'blog']